macro(config_openssl opensslPath)
    if(BUILD_OPENSSL)
        include_directories(${CMAKE_CURRENT_BINARY_DIR}/openssl/include)
    else()
        include_directories(${CMAKE_CURRENT_BINARY_DIR}/${opensslPath}/openssl-prefix/src/openssl/${PREBUILT_BRANCH}/include)
    endif()
endmacro()
